1. CREATE TABLE categories(
   CATEGORIES_ID INT AUTO_INCREMENT PRIMARY KEY,
   CATEGORIES_NAME VARCHAR(255));

2. CREATE TABLE BOOKS(
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_NAME VARCHAR(255),
    CATEGORIES_ID INT,
    FOREIGN KEY (CATEGORIES_ID) REFERENCES categories(CATEGORIES_ID));

3. CREATE INDEX INDX
   ON books(BOOK_NAME);

4. SHOW INDEXES FROM books;