1. CREATE DATABASE BookStoreDB;

2. USE BookStoreDB;

3. CREATE TABLE AUTHORS (
  AUTHOR_ID INT PRIMARY KEY,
  NAME VARCHAR(255),
  COUNTRY VARCHAR(255));

4.CREATE TABLE books (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255),
  PRICE DECIMAL(10,2),
  AUTHOR_ID INT,
  FOREIGN KEY (AUTHOR_ID) REFERENCES authors(AUTHOR_ID));

5. ALTER TABLE books
ADD PUBLISHED_YEAR INT;

6. DELETE FROM books;

7. DROP DATABASE bookstoredb;