1. CREATE DATABASE book_sore;

2. USE book_sore;

3.  CREATE TABLE AUTHORS(
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UNIQUE(EMAIL));

4. CREATE TABLE books(
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    BOOK_TITLE VARCHAR(255),
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors(AUHTOR_ID));