1. CREATE TABLE AUTHORS(
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255));

2. CREATE TABLE BOOK(
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors (AUTHOR_ID));

3. CREATE INDEX INDX ON book (AUTHOR_ID);
