1. CREATE TABLE students(
   STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(255),
   EMAIL VARCHAR(255));

2.  CREATE TABLE course(
    COURSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COURSE_NAME VARCHAR(255));
    
3. CREATE TABLE enrollments(
    ENTROLLMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT(10) NOT NULL,
    COURSE_ID INT(255) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES students(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES course(COURSE_ID));
    